version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker_files/ruby
    environment:
      APP_DATABASE_HOST: db
      APP_DATABASE_USERNAME: postgres
      APP_DATABASE_PASSWORD: postgres123
      TEST_SELENIUM_SERVER: selenium_server
      TEST_WEB_SERVER: web
      TEST_REDIS_SERVER: redis
    volumes:
      - .:/app
      - app_bundle:/usr/local/bundle
    command: "bundle exec pumactl start -F config/puma/development.rb "
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:14.6
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_INITDB_ARGS: "-E UTF8"
      TZ: "Asia/Tokyo"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  selenium_server:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
      - 7900:7900
    environment:
      - SE_NODE_MAX_SESSIONS=2
    shm_size: "2gb"

  web:
    build:
      context: .
      dockerfile: ./docker_files/nginx
    volumes:
      - ./spec/fixtures/html:/usr/share/nginx/html
    ports:
      - 8080:80

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  app_bundle:
    external: false
  db_data:
    external: false
