:scheduler:
  :schedule:
    loto6_latest:
      cron: '0 0 0 * * 5'
      class: Loto6::LatestRegistrationJob
      enabled: <%= ENV.fetch('RAILS_ENV', 'development') == 'production' %>
    loto6_all:
      class: Loto6::AllRegistrationJob
      enabled: false