redis:
  host: localhost
  port: 6379
  db_index: 1
loto:
  loto6:
    latest: https://www.mizuhobank.co.jp/retail/takarakuji/check/loto/loto6/index.html
    back_number: https://www.mizuhobank.co.jp/retail/takarakuji/check/loto/backnumber/index.html
discord:
  notification:
    webhook_url: <%= Rails.application.credentials.production[:discord][:notification][:webhook_url] %>
jobs:
  loto6_registration_job:
    sleep: 2
