redis:
  host: <%= ENV.fetch('TEST_REDIS_SERVER', nil) %>
  port: 6379
  db_index: 1
loto:
  loto6:
    latest: http://<%= ENV.fetch('TEST_WEB_SERVER', nil) %>/loto/loto6/index_multiple.html
    back_number: "http://<%= ENV.fetch('TEST_WEB_SERVER', nil) %>/loto/backnumber/index.html"
