redis:
  host: <%= ENV.fetch('TEST_REDIS_SERVER', nil) %>
  port: 6379
  db_index: 1
loto:
  loto6:
    latest: http://<%= ENV.fetch('TEST_WEB_SERVER', nil) %>/loto/loto6/index_multiple.html
    back_number: http://<%= ENV.fetch('TEST_WEB_SERVER', nil) %>/loto/backnumber/index.html
discord:
  notification:
    webhook_url: <%= Rails.application.credentials.test[:discord][:notification][:webhook_url] %>
jobs:
  loto6_registration_job:
    sleep: 0
  loto_result_creation_job:
    path: tmp/cache/files/test/lotos
